version: "3.9"

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "33060:3306"
    environment:
        MYSQL_USER: root
        MYSQL_PASSWORD: secret
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: pharmacy